version: '3.7'
services:
  nginx:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "443:443"
    command: sh -c "nginx && tail -f /var/log/nginx/error.log"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./openssl.cnf:/etc/ssl/openssl.cnf
      - ./kms.yml:/etc/kms.d/kms.yml
      - ./credentials.json:/etc/kms.d/credentials.json
      - ./kms.crt:/etc/certs/kms.crt
      - ./random-ec.crt:/etc/certs/random-ec.crt
      - ./kms.module:/usr/share/p11-kit/modules/kms.module
