version: '3.8'
services:
  nginx:
    build:
      context: .
    ports:
      - '10443:443'
      - '10080:80'
    volumes:
      - ./certs:/etc/certs
      - ./kms-logs:/var/log/kms
      - ./conf/nginx:/etc/nginx
      - ./conf/openssl:/etc/openssl
      - ./conf/p11-kit:/etc/pkcs11
